# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to Ivan Lopes's Homepage
email: ivanlopes@id.uff.br
description: > # this means to ignore newlines until "baseurl:"
  Todos os meus textos e trabalhos sempre estiveram confinados a academia e ao
  mercado de trabalho, sendo assim, resolvi criar este blog para compartilhar
  estes trabalho e  discutir tópicos relacionados a engenharia elétrica e
  ciências correlatas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ivanlopes.eng.br" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lopesivan

# Build settings
markdown: kramdown
